name: Auto Update README

on:
  schedule:
    - cron: "*/1 * * * *" 
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Append space to README
        run: |
          echo "Appending space..."
          echo " " >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Increase rewards" || echo "Nothing to commit"
          git push
